### ISSUE TITLE
Ship spawned with root part on weird angle

### ISSUE THREAD

**Issue by triffid** [skykooler/Extraplanetary-Launchpads#49]
https://gist.github.com/triffid/8295943 contains a craft file for a ship I'm trying to spawn using the orbital construction dock.

When spawned, the root part (the smallest manned command pod) is on a weird angle- see http://i.imgur.com/fo7ahVX.png

The root part is oriented correctly when opened in the VAB, see http://i.imgur.com/d2wO4FV.png

If I fly it anyway, it seems ok at first, but twists itself into a pretzel and breaks apart when I drop out of warp, and the SAS just wanders all over the place and never settles down. Not sure if this is KSP itself being weird or related to ship being spawned strangely.

**Comment by skykooler** [comment]
I suggest you report this bug on [taniwha's github.](https://github.com/taniwha-qf/Extraplanetary-Launchpads/issues)

**Comment by triffid** [comment]
yeah sorry I followed an old link from somwhere, he's on the case I think
